### PR TITLE
Sphinx-quickstart setup

### PR DESCRIPTION
**Pull request by mtiley**
- add source files for scalar_dynam and ar1_processes
 - edit readme

@mmcky do we want _build to be tracked or just done locally? Obviously I have added it here but having second thoughts
Also having second thoughts about not having a separate source folder for neatness reasons - do you want me to add this?

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @mtiley I will merge this then add `_build` to the ignore.

**Comment by mmcky** [comment]
i think it would be great to have a source folder. Do you want to make that amendment before I merge?

**Comment by mtiley** [comment]
Sure

**Comment by mmcky** [comment]
thanks @mtiley

**Pull request merged**
